# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '>=10.15.0'

- script: |
     npm run build
  displayName: 'Build'

- script: |
    echo Deploy...
    echo See https://aka.ms/yaml
  displayName: 'Deploy'
